const users = [
    'Steven Spielberg',
    'Guillermo del Toro',
    'Christopher Nolan',
    'Martin Scorsese',
    'Quentin Tarantino',
    'Stanley Kubrick',
    'Alfred Hitchcock',
    'Francis Ford Coppola',
    'James Cameron',
    'Ridley Scott',
    'David Lynch',
    'Joel and Ethan Coen',
    'Tim Burton',
    'Wes Anderson',
    'Spike Lee',
    'Darren Aronofsky',
    'Pedro Almodóvar',
    'Sofia Coppola',
    'Spike Jonze',
    'Lynne Ramsay',
    'Alejandro González Iñárritu',
    'Kathryn Bigelow',
    'Greta Gerwig',
    'Barry Jenkins',
    'Jordan Peele',
    'Bong Joon-ho',
    'Chloé Zhao',
];

export default users;
