const tags = [
    'The Godfather',
    'Schindler\'s List',
    'The Shawshank Redemption',
    'The Dark Knight',
    'Pulp Fiction',
    'The Lord of the Rings: The Return of the King',
    'Forrest Gump',
    'Inception',
    'The Matrix',
    'Star Wars: Episode IV - A New Hope',
    'Goodfellas',
    'Fight Club',
    'The Silence of the Lambs',
    'Saving Private Ryan',
    'The Green Mile',
    'Gladiator',
    'The Departed',
    'The Prestige',
    'Interstellar',
    'The Lion King',
    'Titanic',
    'Jurassic Park',
    'Back to the Future',
    'Indiana Jones and the Raiders of the Lost Ark',
    'The Terminator',
    'Die Hard',
    'Alien',
    'Blade Runner',
    'The Exorcist',
    'Jaws',
];

export default tags;
